package com.myspace.nsp_registration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Student implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private int schemeChoice;
	private java.lang.String msg;
	private java.lang.String studentRegId;
	private int stateDomicile;
	private int scholarshipCategory;
	private int scholarshiptypes;
	private int schemeType;
	private java.lang.String studentName;
	private java.lang.String dateOfBirth;
	private java.lang.String gender;
	private int religion;
	private int category;
	private java.lang.String fatherName;
	private java.lang.String motherName;
	private java.lang.Integer annualFamilyIncome;
	private java.lang.String aadharNumber;
	private java.lang.Long mobileNumber;
	private java.lang.String emailAddress;
	private boolean isHosteler;
	private boolean isOrphan;
	private java.lang.String gaurdianName;
	private int modeofStudey;
	private boolean isSingleGirlChild;
	private java.lang.String rank_university_id;
	private int rank_passing_yr;
	private int rank_subject;
	private int lic_state_id;
	private java.lang.String lic_policy_no;
	private java.lang.String lic_id;
	private java.lang.String confirmBankAcccountNO;

	private boolean isDisabled;
	private int typeOfDisability;
	private int percentageOfDisabilty;
	private int maritalStatus;
	private int parentProfession;
	private java.lang.String ifscCode;
	private java.lang.String bankAcccountNO;
	private java.lang.String nameAsInAadhhar;
	private int stateComp;
	private java.lang.String competitiveRollno;
	private java.lang.String bankName;
	private long presentInstitute;
	private long presentBoardUniversity;
	private int presentClass;
	private int presentClassYr;
	private int presentCouse;
	private int presentCouseYear;
	private java.lang.String aadhaar_number;
	private java.lang.String classStartDate;
	private java.lang.Integer prevClassMarks;
	private java.lang.Integer prevBoardUniversity;
	private int prevClass;
	private int prevCouse;
	private java.lang.String prevCourseYear;
	private java.lang.Double prevClassPercentage;
	private int x_Board;
	private int x_Institute;
	private java.lang.Integer x_CourseYear;
	private double x_percentage;
	private java.lang.String x_roll_no;
	private int xii_Board;
	private int xii_Institute;
	private java.lang.Integer xii_CourseYear;
	private double xii_percentage;
	private java.lang.String xii_roll_no;
	private int perStateId;
	private int perDistrictId;
	private int perBlockId;
	private int perVillageId;
	private java.lang.String perAddress;
	private java.lang.Integer perPinCode;
	private int courseLevel;
	private int instituteType;
	private java.lang.String eid;
	private java.lang.String eiddateTime;
	private java.lang.String eidOpt;
	private java.io.File bankProofDoc;
	private java.io.File eidProofDoc;

	private java.lang.String bankProofDocContentType;
	private java.lang.String bankProofDocFileName;
	private java.lang.String eidProofDocContentType;
	private java.lang.String eidProofDocFileName;
	private long fileSize;
	private java.lang.String submit;
	private java.lang.String stateDomicileName;
	private java.lang.String scholarshipCategoryName;
	private java.lang.String genderName;
	private java.lang.String religionName;
	private java.lang.String categoryName;
	private java.lang.String isHostelerName;
	private java.lang.String isOrphanName;
	private java.lang.String isDisabledName;
	private java.lang.String typeOfDisabilityName;
	private java.lang.String maritalStatusName;
	private java.lang.String parentProfessionName;
	private int competitiveExam;
	private java.lang.Integer competitiveExamYear;
	private java.lang.Integer competitiveScore;
	private java.lang.Integer admissionFee;
	private java.lang.Integer tuitionFee;
	private java.lang.Integer miscFee;
	private java.lang.String w_parent_name;
	private java.lang.String w_pppNo;
	private int w_category;
	private java.lang.String w_ForceNo;
	private int w_rank;
	private java.lang.String w_other;
	private java.lang.String w_serving_retired;
	private int forcetype;
	private java.lang.String railway_division;
	private int r_category;
	private int r_rank;
	private int railwayZone;
	private java.lang.String w_unit_last_unit;
	private java.lang.String r_parent_name;
	private java.lang.String r_ForceNo;
	private java.lang.String r_pppNo;
	private java.lang.String aadhaar_virtual_id;
	private java.lang.String aadhaar_registration_mode;
	private java.lang.String aadhaar_token_no;
    public Student() {
    }

    public int getSchemeChoice() {
		return this.schemeChoice;
	}

	public void setSchemeChoice(int schemeChoice) {
		this.schemeChoice = schemeChoice;
	}

	public java.lang.String getMsg() {
		return this.msg;
	}

	public void setMsg(java.lang.String msg) {
		this.msg = msg;
	}

	public java.lang.String getStudentRegId() {
		return this.studentRegId;
	}

	public void setStudentRegId(java.lang.String studentRegId) {
		this.studentRegId = studentRegId;
	}

	public int getStateDomicile() {
		return this.stateDomicile;
	}

	public void setStateDomicile(int stateDomicile) {
		this.stateDomicile = stateDomicile;
	}

	public int getScholarshipCategory() {
		return this.scholarshipCategory;
	}

	public void setScholarshipCategory(int scholarshipCategory) {
		this.scholarshipCategory = scholarshipCategory;
	}

	public int getScholarshiptypes() {
		return this.scholarshiptypes;
	}

	public void setScholarshiptypes(int scholarshiptypes) {
		this.scholarshiptypes = scholarshiptypes;
	}

	public int getSchemeType() {
		return this.schemeType;
	}

	public void setSchemeType(int schemeType) {
		this.schemeType = schemeType;
	}

	public java.lang.String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(java.lang.String studentName) {
		this.studentName = studentName;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public int getReligion() {
		return this.religion;
	}

	public void setReligion(int religion) {
		this.religion = religion;
	}

	public int getCategory() {
		return this.category;
	}

	public void setCategory(int category) {
		this.category = category;
	}

	public java.lang.String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(java.lang.String fatherName) {
		this.fatherName = fatherName;
	}

	public java.lang.String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(java.lang.String motherName) {
		this.motherName = motherName;
	}

	public java.lang.Integer getAnnualFamilyIncome() {
		return this.annualFamilyIncome;
	}

	public void setAnnualFamilyIncome(java.lang.Integer annualFamilyIncome) {
		this.annualFamilyIncome = annualFamilyIncome;
	}

	public java.lang.String getAadharNumber() {
		return this.aadharNumber;
	}

	public void setAadharNumber(java.lang.String aadharNumber) {
		this.aadharNumber = aadharNumber;
	}

	public java.lang.Long getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(java.lang.Long mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public java.lang.String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(java.lang.String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public boolean isIsHosteler() {
		return this.isHosteler;
	}

	public void setIsHosteler(boolean isHosteler) {
		this.isHosteler = isHosteler;
	}

	public boolean isIsOrphan() {
		return this.isOrphan;
	}

	public void setIsOrphan(boolean isOrphan) {
		this.isOrphan = isOrphan;
	}

	public java.lang.String getGaurdianName() {
		return this.gaurdianName;
	}

	public void setGaurdianName(java.lang.String gaurdianName) {
		this.gaurdianName = gaurdianName;
	}

	public int getModeofStudey() {
		return this.modeofStudey;
	}

	public void setModeofStudey(int modeofStudey) {
		this.modeofStudey = modeofStudey;
	}

	public boolean isIsSingleGirlChild() {
		return this.isSingleGirlChild;
	}

	public void setIsSingleGirlChild(boolean isSingleGirlChild) {
		this.isSingleGirlChild = isSingleGirlChild;
	}

	public java.lang.String getRank_university_id() {
		return this.rank_university_id;
	}

	public void setRank_university_id(java.lang.String rank_university_id) {
		this.rank_university_id = rank_university_id;
	}

	public int getRank_passing_yr() {
		return this.rank_passing_yr;
	}

	public void setRank_passing_yr(int rank_passing_yr) {
		this.rank_passing_yr = rank_passing_yr;
	}

	public int getRank_subject() {
		return this.rank_subject;
	}

	public void setRank_subject(int rank_subject) {
		this.rank_subject = rank_subject;
	}

	public int getLic_state_id() {
		return this.lic_state_id;
	}

	public void setLic_state_id(int lic_state_id) {
		this.lic_state_id = lic_state_id;
	}

	public java.lang.String getLic_policy_no() {
		return this.lic_policy_no;
	}

	public void setLic_policy_no(java.lang.String lic_policy_no) {
		this.lic_policy_no = lic_policy_no;
	}

	public java.lang.String getLic_id() {
		return this.lic_id;
	}

	public void setLic_id(java.lang.String lic_id) {
		this.lic_id = lic_id;
	}

	public java.lang.String getConfirmBankAcccountNO() {
		return this.confirmBankAcccountNO;
	}

	public void setConfirmBankAcccountNO(java.lang.String confirmBankAcccountNO) {
		this.confirmBankAcccountNO = confirmBankAcccountNO;
	}

	public boolean isIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	public int getTypeOfDisability() {
		return this.typeOfDisability;
	}

	public void setTypeOfDisability(int typeOfDisability) {
		this.typeOfDisability = typeOfDisability;
	}

	public int getPercentageOfDisabilty() {
		return this.percentageOfDisabilty;
	}

	public void setPercentageOfDisabilty(int percentageOfDisabilty) {
		this.percentageOfDisabilty = percentageOfDisabilty;
	}

	public int getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(int maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public int getParentProfession() {
		return this.parentProfession;
	}

	public void setParentProfession(int parentProfession) {
		this.parentProfession = parentProfession;
	}

	public java.lang.String getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(java.lang.String ifscCode) {
		this.ifscCode = ifscCode;
	}

	public java.lang.String getBankAcccountNO() {
		return this.bankAcccountNO;
	}

	public void setBankAcccountNO(java.lang.String bankAcccountNO) {
		this.bankAcccountNO = bankAcccountNO;
	}

	public java.lang.String getNameAsInAadhhar() {
		return this.nameAsInAadhhar;
	}

	public void setNameAsInAadhhar(java.lang.String nameAsInAadhhar) {
		this.nameAsInAadhhar = nameAsInAadhhar;
	}

	public int getStateComp() {
		return this.stateComp;
	}

	public void setStateComp(int stateComp) {
		this.stateComp = stateComp;
	}

	public java.lang.String getCompetitiveRollno() {
		return this.competitiveRollno;
	}

	public void setCompetitiveRollno(java.lang.String competitiveRollno) {
		this.competitiveRollno = competitiveRollno;
	}

	public java.lang.String getBankName() {
		return this.bankName;
	}

	public void setBankName(java.lang.String bankName) {
		this.bankName = bankName;
	}

	public long getPresentInstitute() {
		return this.presentInstitute;
	}

	public void setPresentInstitute(long presentInstitute) {
		this.presentInstitute = presentInstitute;
	}

	public long getPresentBoardUniversity() {
		return this.presentBoardUniversity;
	}

	public void setPresentBoardUniversity(long presentBoardUniversity) {
		this.presentBoardUniversity = presentBoardUniversity;
	}

	public int getPresentClass() {
		return this.presentClass;
	}

	public void setPresentClass(int presentClass) {
		this.presentClass = presentClass;
	}

	public int getPresentClassYr() {
		return this.presentClassYr;
	}

	public void setPresentClassYr(int presentClassYr) {
		this.presentClassYr = presentClassYr;
	}

	public int getPresentCouse() {
		return this.presentCouse;
	}

	public void setPresentCouse(int presentCouse) {
		this.presentCouse = presentCouse;
	}

	public int getPresentCouseYear() {
		return this.presentCouseYear;
	}

	public void setPresentCouseYear(int presentCouseYear) {
		this.presentCouseYear = presentCouseYear;
	}

	public java.lang.String getAadhaar_number() {
		return this.aadhaar_number;
	}

	public void setAadhaar_number(java.lang.String aadhaar_number) {
		this.aadhaar_number = aadhaar_number;
	}

	public java.lang.String getClassStartDate() {
		return this.classStartDate;
	}

	public void setClassStartDate(java.lang.String classStartDate) {
		this.classStartDate = classStartDate;
	}

	public java.lang.Integer getPrevClassMarks() {
		return this.prevClassMarks;
	}

	public void setPrevClassMarks(java.lang.Integer prevClassMarks) {
		this.prevClassMarks = prevClassMarks;
	}

	public java.lang.Integer getPrevBoardUniversity() {
		return this.prevBoardUniversity;
	}

	public void setPrevBoardUniversity(java.lang.Integer prevBoardUniversity) {
		this.prevBoardUniversity = prevBoardUniversity;
	}

	public int getPrevClass() {
		return this.prevClass;
	}

	public void setPrevClass(int prevClass) {
		this.prevClass = prevClass;
	}

	public int getPrevCouse() {
		return this.prevCouse;
	}

	public void setPrevCouse(int prevCouse) {
		this.prevCouse = prevCouse;
	}

	public java.lang.String getPrevCourseYear() {
		return this.prevCourseYear;
	}

	public void setPrevCourseYear(java.lang.String prevCourseYear) {
		this.prevCourseYear = prevCourseYear;
	}

	public java.lang.Double getPrevClassPercentage() {
		return this.prevClassPercentage;
	}

	public void setPrevClassPercentage(java.lang.Double prevClassPercentage) {
		this.prevClassPercentage = prevClassPercentage;
	}

	public int getX_Board() {
		return this.x_Board;
	}

	public void setX_Board(int x_Board) {
		this.x_Board = x_Board;
	}

	public int getX_Institute() {
		return this.x_Institute;
	}

	public void setX_Institute(int x_Institute) {
		this.x_Institute = x_Institute;
	}

	public java.lang.Integer getX_CourseYear() {
		return this.x_CourseYear;
	}

	public void setX_CourseYear(java.lang.Integer x_CourseYear) {
		this.x_CourseYear = x_CourseYear;
	}

	public double getX_percentage() {
		return this.x_percentage;
	}

	public void setX_percentage(double x_percentage) {
		this.x_percentage = x_percentage;
	}

	public java.lang.String getX_roll_no() {
		return this.x_roll_no;
	}

	public void setX_roll_no(java.lang.String x_roll_no) {
		this.x_roll_no = x_roll_no;
	}

	public int getXii_Board() {
		return this.xii_Board;
	}

	public void setXii_Board(int xii_Board) {
		this.xii_Board = xii_Board;
	}

	public int getXii_Institute() {
		return this.xii_Institute;
	}

	public void setXii_Institute(int xii_Institute) {
		this.xii_Institute = xii_Institute;
	}

	public java.lang.Integer getXii_CourseYear() {
		return this.xii_CourseYear;
	}

	public void setXii_CourseYear(java.lang.Integer xii_CourseYear) {
		this.xii_CourseYear = xii_CourseYear;
	}

	public double getXii_percentage() {
		return this.xii_percentage;
	}

	public void setXii_percentage(double xii_percentage) {
		this.xii_percentage = xii_percentage;
	}

	public java.lang.String getXii_roll_no() {
		return this.xii_roll_no;
	}

	public void setXii_roll_no(java.lang.String xii_roll_no) {
		this.xii_roll_no = xii_roll_no;
	}

	public int getPerStateId() {
		return this.perStateId;
	}

	public void setPerStateId(int perStateId) {
		this.perStateId = perStateId;
	}

	public int getPerDistrictId() {
		return this.perDistrictId;
	}

	public void setPerDistrictId(int perDistrictId) {
		this.perDistrictId = perDistrictId;
	}

	public int getPerBlockId() {
		return this.perBlockId;
	}

	public void setPerBlockId(int perBlockId) {
		this.perBlockId = perBlockId;
	}

	public int getPerVillageId() {
		return this.perVillageId;
	}

	public void setPerVillageId(int perVillageId) {
		this.perVillageId = perVillageId;
	}

	public java.lang.String getPerAddress() {
		return this.perAddress;
	}

	public void setPerAddress(java.lang.String perAddress) {
		this.perAddress = perAddress;
	}

	public java.lang.Integer getPerPinCode() {
		return this.perPinCode;
	}

	public void setPerPinCode(java.lang.Integer perPinCode) {
		this.perPinCode = perPinCode;
	}

	public int getCourseLevel() {
		return this.courseLevel;
	}

	public void setCourseLevel(int courseLevel) {
		this.courseLevel = courseLevel;
	}

	public int getInstituteType() {
		return this.instituteType;
	}

	public void setInstituteType(int instituteType) {
		this.instituteType = instituteType;
	}

	public java.lang.String getEid() {
		return this.eid;
	}

	public void setEid(java.lang.String eid) {
		this.eid = eid;
	}

	public java.lang.String getEiddateTime() {
		return this.eiddateTime;
	}

	public void setEiddateTime(java.lang.String eiddateTime) {
		this.eiddateTime = eiddateTime;
	}

	public java.lang.String getEidOpt() {
		return this.eidOpt;
	}

	public void setEidOpt(java.lang.String eidOpt) {
		this.eidOpt = eidOpt;
	}

	public java.io.File getEidProofDoc() {
		return eidProofDoc;
	}

	public void setEidProofDoc(java.io.File eidProofDoc) {
		this.eidProofDoc = eidProofDoc;
	}

	public java.io.File getBankProofDoc() {
		return bankProofDoc;
	}

	public void setBankProofDoc(java.io.File bankProofDoc) {
		this.bankProofDoc = bankProofDoc;
	}

	public java.lang.String getBankProofDocContentType() {
		return this.bankProofDocContentType;
	}

	public void setBankProofDocContentType(
			java.lang.String bankProofDocContentType) {
		this.bankProofDocContentType = bankProofDocContentType;
	}

	public java.lang.String getBankProofDocFileName() {
		return this.bankProofDocFileName;
	}

	public void setBankProofDocFileName(java.lang.String bankProofDocFileName) {
		this.bankProofDocFileName = bankProofDocFileName;
	}

	public java.lang.String getEidProofDocContentType() {
		return this.eidProofDocContentType;
	}

	public void setEidProofDocContentType(
			java.lang.String eidProofDocContentType) {
		this.eidProofDocContentType = eidProofDocContentType;
	}

	public java.lang.String getEidProofDocFileName() {
		return this.eidProofDocFileName;
	}

	public void setEidProofDocFileName(java.lang.String eidProofDocFileName) {
		this.eidProofDocFileName = eidProofDocFileName;
	}

	public long getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(long fileSize) {
		this.fileSize = fileSize;
	}

	public java.lang.String getSubmit() {
		return this.submit;
	}

	public void setSubmit(java.lang.String submit) {
		this.submit = submit;
	}

	public java.lang.String getStateDomicileName() {
		return this.stateDomicileName;
	}

	public void setStateDomicileName(java.lang.String stateDomicileName) {
		this.stateDomicileName = stateDomicileName;
	}

	public java.lang.String getScholarshipCategoryName() {
		return this.scholarshipCategoryName;
	}

	public void setScholarshipCategoryName(
			java.lang.String scholarshipCategoryName) {
		this.scholarshipCategoryName = scholarshipCategoryName;
	}

	public java.lang.String getGenderName() {
		return this.genderName;
	}

	public void setGenderName(java.lang.String genderName) {
		this.genderName = genderName;
	}

	public java.lang.String getReligionName() {
		return this.religionName;
	}

	public void setReligionName(java.lang.String religionName) {
		this.religionName = religionName;
	}

	public java.lang.String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(java.lang.String categoryName) {
		this.categoryName = categoryName;
	}

	public java.lang.String getIsHostelerName() {
		return this.isHostelerName;
	}

	public void setIsHostelerName(java.lang.String isHostelerName) {
		this.isHostelerName = isHostelerName;
	}

	public java.lang.String getIsOrphanName() {
		return this.isOrphanName;
	}

	public void setIsOrphanName(java.lang.String isOrphanName) {
		this.isOrphanName = isOrphanName;
	}

	public java.lang.String getIsDisabledName() {
		return this.isDisabledName;
	}

	public void setIsDisabledName(java.lang.String isDisabledName) {
		this.isDisabledName = isDisabledName;
	}

	public java.lang.String getTypeOfDisabilityName() {
		return this.typeOfDisabilityName;
	}

	public void setTypeOfDisabilityName(java.lang.String typeOfDisabilityName) {
		this.typeOfDisabilityName = typeOfDisabilityName;
	}

	public java.lang.String getMaritalStatusName() {
		return this.maritalStatusName;
	}

	public void setMaritalStatusName(java.lang.String maritalStatusName) {
		this.maritalStatusName = maritalStatusName;
	}

	public java.lang.String getParentProfessionName() {
		return this.parentProfessionName;
	}

	public void setParentProfessionName(java.lang.String parentProfessionName) {
		this.parentProfessionName = parentProfessionName;
	}

	public int getCompetitiveExam() {
		return this.competitiveExam;
	}

	public void setCompetitiveExam(int competitiveExam) {
		this.competitiveExam = competitiveExam;
	}

	public java.lang.Integer getCompetitiveExamYear() {
		return this.competitiveExamYear;
	}

	public void setCompetitiveExamYear(java.lang.Integer competitiveExamYear) {
		this.competitiveExamYear = competitiveExamYear;
	}

	public java.lang.Integer getCompetitiveScore() {
		return this.competitiveScore;
	}

	public void setCompetitiveScore(java.lang.Integer competitiveScore) {
		this.competitiveScore = competitiveScore;
	}

	public java.lang.Integer getAdmissionFee() {
		return this.admissionFee;
	}

	public void setAdmissionFee(java.lang.Integer admissionFee) {
		this.admissionFee = admissionFee;
	}

	public java.lang.Integer getTuitionFee() {
		return this.tuitionFee;
	}

	public void setTuitionFee(java.lang.Integer tuitionFee) {
		this.tuitionFee = tuitionFee;
	}

	public java.lang.Integer getMiscFee() {
		return this.miscFee;
	}

	public void setMiscFee(java.lang.Integer miscFee) {
		this.miscFee = miscFee;
	}

	public java.lang.String getW_parent_name() {
		return this.w_parent_name;
	}

	public void setW_parent_name(java.lang.String w_parent_name) {
		this.w_parent_name = w_parent_name;
	}

	public java.lang.String getW_pppNo() {
		return this.w_pppNo;
	}

	public void setW_pppNo(java.lang.String w_pppNo) {
		this.w_pppNo = w_pppNo;
	}

	public int getW_category() {
		return this.w_category;
	}

	public void setW_category(int w_category) {
		this.w_category = w_category;
	}

	public java.lang.String getW_ForceNo() {
		return this.w_ForceNo;
	}

	public void setW_ForceNo(java.lang.String w_ForceNo) {
		this.w_ForceNo = w_ForceNo;
	}

	public int getW_rank() {
		return this.w_rank;
	}

	public void setW_rank(int w_rank) {
		this.w_rank = w_rank;
	}

	public java.lang.String getW_other() {
		return this.w_other;
	}

	public void setW_other(java.lang.String w_other) {
		this.w_other = w_other;
	}

	public java.lang.String getW_serving_retired() {
		return this.w_serving_retired;
	}

	public void setW_serving_retired(java.lang.String w_serving_retired) {
		this.w_serving_retired = w_serving_retired;
	}

	public int getForcetype() {
		return this.forcetype;
	}

	public void setForcetype(int forcetype) {
		this.forcetype = forcetype;
	}

	public java.lang.String getRailway_division() {
		return this.railway_division;
	}

	public void setRailway_division(java.lang.String railway_division) {
		this.railway_division = railway_division;
	}

	public int getR_category() {
		return this.r_category;
	}

	public void setR_category(int r_category) {
		this.r_category = r_category;
	}

	public int getR_rank() {
		return this.r_rank;
	}

	public void setR_rank(int r_rank) {
		this.r_rank = r_rank;
	}

	public int getRailwayZone() {
		return this.railwayZone;
	}

	public void setRailwayZone(int railwayZone) {
		this.railwayZone = railwayZone;
	}

	public java.lang.String getW_unit_last_unit() {
		return this.w_unit_last_unit;
	}

	public void setW_unit_last_unit(java.lang.String w_unit_last_unit) {
		this.w_unit_last_unit = w_unit_last_unit;
	}

	public java.lang.String getR_parent_name() {
		return this.r_parent_name;
	}

	public void setR_parent_name(java.lang.String r_parent_name) {
		this.r_parent_name = r_parent_name;
	}

	public java.lang.String getR_ForceNo() {
		return this.r_ForceNo;
	}

	public void setR_ForceNo(java.lang.String r_ForceNo) {
		this.r_ForceNo = r_ForceNo;
	}

	public java.lang.String getR_pppNo() {
		return this.r_pppNo;
	}

	public void setR_pppNo(java.lang.String r_pppNo) {
		this.r_pppNo = r_pppNo;
	}

	public java.lang.String getAadhaar_virtual_id() {
		return this.aadhaar_virtual_id;
	}

	public void setAadhaar_virtual_id(java.lang.String aadhaar_virtual_id) {
		this.aadhaar_virtual_id = aadhaar_virtual_id;
	}

	public java.lang.String getAadhaar_registration_mode() {
		return this.aadhaar_registration_mode;
	}

	public void setAadhaar_registration_mode(
			java.lang.String aadhaar_registration_mode) {
		this.aadhaar_registration_mode = aadhaar_registration_mode;
	}

	public java.lang.String getAadhaar_token_no() {
		return this.aadhaar_token_no;
	}

	public void setAadhaar_token_no(java.lang.String aadhaar_token_no) {
		this.aadhaar_token_no = aadhaar_token_no;
	}


}